### ISSUE TITLE
burnout is distracting

### ISSUE THREAD

**Issue by nitinthewiz** [karissa/karissamck.com#2]
Hey Karissa. I came across your profile/site from the dat-server repo.

I noticed something on the site - upon clicking 'you' in the chart, the burnout class is activated and your PGP key drops in. This is cool and helpful, specially if someone is trying to contact you. But there's no way to disable burnout other than to refresh the page. 

While this is a pretty awesome call to action, it's rather distracting and not user friendly. Therefore, I'm wondering if you'll reconsider this and change the functionality to something else, perhaps clicking 'you' again to disable burnout.

I didn't submit a pull request as I don't want to muck around your code without you approving the kind of change which should be in place. Looking forward to your thoughts on this.

Nitin

**Comment by okdistribute** [comment]
I fixed it! Thanks, check it out now and tell me what you think.

**Comment by nitinthewiz** [comment]
I see that you've removed the PGP section. I suppose if you're not using it a lot/ others aren't using it to contact you then all's well...

**Comment by okdistribute** [comment]
It's on the keyserver. I'll put my fingerprint online

**Comment by nitinthewiz** [comment]
Good to know!
